# Theme: Clay
# Adapted for Omarchy

theme[main_bg]="#1a1515"
theme[main_fg]="#dcc9bc"
theme[title]="#ffe9c7"
theme[hi_fg]="#e39c45"

theme[selected_bg]="#2d2424"
theme[selected_fg]="#ffe9c7"
theme[inactive_fg]="#725a5a"
theme[proc_misc]="#f07342"

theme[cpu_box]="#453636"
theme[mem_box]="#453636"
theme[net_box]="#453636"
theme[proc_box]="#453636"
theme[div_line]="#453636"

theme[temp_start]="#959a6b"
theme[temp_mid]="#e39c45"
theme[temp_end]="#cf223e"

theme[cpu_start]="#768f80"
theme[cpu_mid]="#959a6b"
theme[cpu_end]="#e39c45"

theme[free_start]="#768f80"
theme[free_mid]="#959a6b"
theme[free_end]="#e39c45"

theme[cached_start]="#756d94"
theme[cached_mid]="#959a6b"
theme[cached_end]="#e39c45"

theme[available_start]="#768f80"
theme[available_mid]="#959a6b"
theme[available_end]="#e39c45"

theme[used_start]="#959a6b"
theme[used_mid]="#e39c45"
theme[used_end]="#cf223e"

theme[download_start]="#768f80"
theme[download_mid]="#959a6b"
theme[download_end]="#e39c45"

theme[upload_start]="#756d94"
theme[upload_mid]="#e39c45"
theme[upload_end]="#cf223e"
