general {
    lock_cmd = omarchy-lock-screen
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
    inhibit_sleep = 3
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
    ignore_inhibit = true
}

listener {
    timeout = 2700
    on-timeout = systemctl suspend
    ignore_inhibit = true
}
